# Generated by Django 3.2.20 on 2023-08-04 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('genre', models.CharField(max_length=50)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='record_covers/')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.artist')),
            ],
        ),
    ]
