# Generated by Django 3.2.20 on 2023-08-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='latest_releases/')),
                ('track_details', models.TextField()),
                ('download_link', models.URLField()),
                ('download_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vinyl_link', models.URLField()),
                ('vinyl_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
