# Generated by Django 3.2.20 on 2023-08-04 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20230804_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestrelease',
            name='artist',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.artist'),
        ),
        migrations.AlterField(
            model_name='latestrelease',
            name='download_link',
            field=models.URLField(default='https://example.com/default-download-link'),
        ),
        migrations.AlterField(
            model_name='latestrelease',
            name='download_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='latestrelease',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='latestrelease',
            name='vinyl_link',
            field=models.URLField(default='https://example.com/default-vinyl-link'),
        ),
        migrations.AlterField(
            model_name='latestrelease',
            name='vinyl_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
