# Generated by Django 3.2.20 on 2023-08-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20230804_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestrelease',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/releases/'),
        ),
    ]
