# Generated by Django 3.2.20 on 2023-08-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_latestrelease_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestrelease',
            name='release_date',
            field=models.DateField(default='2023-08-04'),
        ),
    ]
