# Generated by Django 3.2.20 on 2023-08-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_latestrelease_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestrelease',
            name='release_date',
            field=models.DateField(),
        ),
    ]
