# Generated by Django 3.2.20 on 2023-08-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_latestrelease_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestrelease',
            name='release_date',
            field=models.DateField(default='2023-08-04'),
        ),
    ]
