# Generated by Django 3.2.20 on 2023-08-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20230804_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='download_link',
            field=models.URLField(default='https://example.com/default-download-link'),
        ),
        migrations.AddField(
            model_name='album',
            name='download_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='album',
            name='vinyl_link',
            field=models.URLField(default='https://example.com/default-vinyl-link'),
        ),
        migrations.AddField(
            model_name='album',
            name='vinyl_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
