# Generated by Django 3.2.20 on 2023-08-04 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20230804_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='download_link',
            field=models.URLField(default='https://example.com/album-download-link'),
        ),
        migrations.AlterField(
            model_name='album',
            name='vinyl_link',
            field=models.URLField(default='https://example.com/album-vinyl-link'),
        ),
        migrations.CreateModel(
            name='Single',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='single_covers/')),
                ('download_link', models.URLField(default='https://example.com/default-download-link')),
                ('download_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.artist')),
            ],
        ),
    ]
