# Generated by Django 3.2.20 on 2023-08-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20230804_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestrelease',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='single',
            name='artist',
        ),
        migrations.AddField(
            model_name='record',
            name='category',
            field=models.CharField(choices=[('ALBUM', 'Album'), ('LATEST', 'Latest Release'), ('SINGLE', 'Single')], default='LATEST', max_length=10),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='LatestRelease',
        ),
        migrations.DeleteModel(
            name='Single',
        ),
    ]
