# Generated by Django 3.2.20 on 2023-08-04 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20230804_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='genre',
        ),
    ]
