# Generated by Django 3.2.20 on 2023-08-04 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20230804_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='download_link',
        ),
        migrations.RemoveField(
            model_name='record',
            name='download_price',
        ),
        migrations.RemoveField(
            model_name='record',
            name='vinyl_link',
        ),
        migrations.RemoveField(
            model_name='record',
            name='vinyl_price',
        ),
    ]
