# Generated by Django 3.2.20 on 2023-08-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20230804_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='download_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='download_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='vinyl_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='vinyl_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
