# Generated by Django 3.2.20 on 2023-08-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_blogpost_link_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='artist_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
